# -*- coding: utf-8 -*-
"""Copy of sheetsense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFRdKQsGSstGBK1nJiwln9FJnMo3FMGC
"""

# ============================================================
# SheetSense AI — Excel Chaos → AI Dashboard in 60 Seconds
# Author: Imran Ntenje
# Version: Gumroad v1.0
# Requires: pandas, plotly, openpyxl
# ============================================================

import pandas as pd
import plotly.express as px
import json
import os
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning)



# -----------------------------
# 1. LOAD FILE
# -----------------------------
def load_file(file_path, sheet_name=None):
    """
    Load Excel (.xlsx) or CSV file.
    Defaults to first sheet if none specified.
    """
    try:
        if file_path.endswith(".csv"):
            df = pd.read_csv(file_path)
        else:
            df = pd.read_excel(
                file_path,
                sheet_name=0 if sheet_name is None else sheet_name,
                engine="openpyxl"
            )
        print(f"✅ Loaded file successfully ({len(df)} rows)")
        return df
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None


# -----------------------------
# 2. AUTO CLEAN DATA
# -----------------------------
def auto_clean(df):
    """
    Automatically clean common Excel issues:
    - Remove empty rows/columns
    - Convert dates
    - Fill numeric NaN values
    """
    print("🧹 Cleaning data...")

    # Drop empty rows/columns
    df = df.dropna(how="all").dropna(axis=1, how="all")

    for col in df.columns:
        # Try converting object columns to datetime
        if df[col].dtype == "object":
            try:
                converted = pd.to_datetime(
                    df[col],
                    errors="coerce",
                    infer_datetime_format=True
                )
                # Only convert if at least 50% looks like dates
                if converted.notna().mean() > 0.5:
                    df[col] = converted
            except Exception:
                pass

        # Fill missing numeric values
        if df[col].dtype in ["int64", "float64"]:
            df[col] = df[col].fillna(0)

    print("✅ Data cleaned")
    return df


# -----------------------------
# 3. GENERATE DASHBOARD
# -----------------------------
def generate_dashboard(df, output_html="dashboard.html"):
    """
    Generate interactive charts automatically.
    """
    print("📊 Generating dashboard...")
    figures = []

    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
    text_cols = df.select_dtypes(include=["object"]).columns

    # Trend or Bar Chart
    if len(numeric_cols) >= 1:
        value_col = numeric_cols[0]
        if len(df) > 1 and df.iloc[:, 0].dtype == "datetime64[ns]":
            fig = px.line(
                df,
                x=df.columns[0],
                y=value_col,
                title=f"Trend Over Time: {value_col}"
            )
        else:
            fig = px.bar(
                df.head(20),
                x=df.head(20).index,
                y=value_col,
                title=f"Top 20 Records: {value_col}"
            )
        figures.append(fig)

    # Category Breakdown
    if len(text_cols) >= 1:
        cat_col = text_cols[0]
        top_values = df[cat_col].value_counts().head(10)
        fig = px.pie(
            values=top_values.values,
            names=top_values.index,
            title=f"Category Breakdown: {cat_col}"
        )
        figures.append(fig)

    # Save HTML
    html = "<html><body>"
    html += "<h1>SheetSense AI Dashboard</h1>"

    for i, fig in enumerate(figures, start=1):
        html += f"<h2>Chart {i}</h2>"
        html += fig.to_html(include_plotlyjs="cdn")

    html += f"<p>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>"
    html += "</body></html>"

    with open(output_html, "w") as f:
        f.write(html)

    print(f"✅ Dashboard saved as {output_html}")
    return output_html, figures


# -----------------------------
# 5. MAIN PROGRAM
# -----------------------------
def main():
    print("\n🚀 SheetSense AI — Excel → AI Dashboard Tool\n")

    file_path = input("📂 Enter Excel/CSV filename (e.g. sales.xlsx): ").strip()

    if not os.path.exists(file_path):
        print("❌ File not found. Upload the file first.")
        return

    df = load_file(file_path)
    if df is None:
        return

    df = auto_clean(df)

    dashboard_file, figures = generate_dashboard(df)

    print("\n🎉 DONE!")
    print("Next steps:")
    print("1️⃣ Open dashboard.html")
    print("🔒 AI insights export available in Pro version → https://imranntenje.gumroad.com/l/sheetsense-ai")


if __name__ == "__main__":
    main()
